package com.example.communication.model

enum class Elsword(val originName: String) {
    Elsword_1("나이트 엠퍼러"),
    Elsword_2("룬 마스터"),
    Elsword_3("임모탈"),
    Elsword_4("제네시스"),
    Aisha_1("에테르 세이지"),
    Aisha_2("오즈 소서러"),
    Aisha_3("메타모르프"),
    Aisha_4("로드 아조트"),
    Rena_1("아네모스"),
    Rena_2("데이브레이커"),
    Rena_3("트와일라잇"),
    Rena_4("프로피티스"),
    Raven_1("퓨리어스 블레이드"),
    Raven_2("레이지 하츠"),
    Raven_3("노바 임퍼레이터"),
    Raven_4("레버넌트"),
    Eve_1("코드:얼티메이트"),
    Eve_2("코드:에센시아"),
    Eve_3("코드:사리엘"),
    Eve_4("코드:안티테제"),
    Chung_1("코멧 크루세이더"),
    Chung_2("페이탈 팬텀"),
    Chung_3("센츄리온"),
    Chung_4("디우스 아에르"),
    Ara_1("비천"),
    Ara_2("범황"),
    Ara_3("대라"),
    Ara_4("일천"),
    Elesis_1("엠파이어 소드"),
    Elesis_2("플레임 로드"),
    Elesis_3("블러드 퀸"),
    Elesis_4("아드레스티아"),
    Add_1("둠 브링어"),
    Add_2("도미네이터"),
    Add_3("매드 패러독스"),
    Add_4("오버마인드"),
    Luciel_1("카타스트로피"),
    Luciel_2("이노센트"),
    Luciel_3("디앙게릴온"),
    Luciel_4("데메르시오"),
    Rose_1("템페스트 버스"),
    Rose_2("블랙 매서커"),
    Rose_3("미네르바"),
    Rose_4("프라임 오퍼레이터"),
    Ain_1("리히터"),
    Ain_2("블루헨"),
    Ain_3("헤르셔"),
    Ain_4("비고트"),
    Laby_1("이터니티 위너"),
    Laby_2("라디언트 소울"),
    Laby_3("니샤 라비린스"),
    Laby_4("트윈즈 피카로"),
    Noah_1("리버레이터"),
    Noah_2("셀레스티아"),
    Noah_3("닉스 피에타"),
    Noah_4("모르페우스"),
}